# Generated by Django 5.0.6 on 2024-05-15 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Author Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Genre Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of books', verbose_name='Stock')),
                ('borrowed_books', models.PositiveIntegerField(default=0, help_text='Number of borrowed books', verbose_name='Borrowed Books')),
                ('authors', models.ManyToManyField(related_name='books', to='library_app.author', verbose_name='Authors')),
                ('genres', models.ManyToManyField(related_name='books', to='library_app.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title', 'published_date'],
            },
        ),
        migrations.CreateModel(
            name='BooksBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True, help_text='Creates automatically', verbose_name='Borrowed Date')),
                ('borrowed_status', models.CharField(choices=[('pending', 'Pending'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=10, verbose_name='Borrowed Status')),
                ('return_date', models.DateTimeField(blank=True, help_text='Date/time of returning borrowed book', null=True, verbose_name='Return Date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='library_app.book', verbose_name='Book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='Borrower')),
            ],
            options={
                'verbose_name': 'Books Borrow',
                'verbose_name_plural': 'Books Borrows',
                'ordering': ['-borrowed_date'],
            },
        ),
    ]
