# Generated by Django 5.0.6 on 2024-05-16 18:39

import django.core.validators
import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_books',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), library_app.models.max_value_current_year], verbose_name='Published Date'),
        ),
    ]
