# Generated by Django 5.0.6 on 2024-05-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_books',
        ),
    ]
