# Generated by Django 5.0.6 on 2024-05-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_book_borrowed_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_books',
            field=models.PositiveIntegerField(default=0, help_text='Number of borrowed books', verbose_name='Borrowed Books'),
        ),
        migrations.AddField(
            model_name='book',
            name='reservation_books',
            field=models.PositiveIntegerField(default=0, help_text='Number of reservation books', verbose_name='Reservation Books'),
        ),
    ]
