# Generated by Django 5.0.6 on 2024-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_booksborrow_reservation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksborrow',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='booksborrow',
            name='borrowed_status',
            field=models.CharField(choices=[('reserved', 'Reserved a book'), ('borrowed', 'Borrowed a book'), ('returned', 'Returned a book'), ('reservation_expired', 'Reservation expired'), ('overdue', 'Overdue borrowed'), ('reservation_canceled', 'Reservation canceled')], default='pending', max_length=50, verbose_name='Borrowed Status'),
        ),
        migrations.DeleteModel(
            name='BookReservation',
        ),
    ]
