# Generated by Django 5.0.6 on 2024-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_remove_book_published_date_book_published_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(1, 'Reserved'), (2, 'Reservation Expired'), (3, 'Reservation Canceled'), (4, 'Wishlist'), (5, 'Picked Up')], default=1, verbose_name='Reservation Status'),
        ),
        migrations.AlterField(
            model_name='booksborrow',
            name='borrowed_status',
            field=models.IntegerField(choices=[(1, 'Borrowed a book'), (2, 'Returned a book'), (3, 'Overdue book'), (4, 'Returned overdue book')], default=1, verbose_name='Borrowed Status'),
        ),
    ]
