# Generated by Django 5.0.6 on 2024-05-19 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_booksborrow_reservation_id_book_image_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksborrow',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='library_app.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='booksborrow',
            name='borrowed_status',
            field=models.CharField(choices=[('borrowed', 'Borrowed a book'), ('returned', 'Returned a book'), ('overdue', 'Overdue borrowed')], default='borrowed', max_length=50, verbose_name='Borrowed Status'),
        ),
        migrations.AlterField(
            model_name='booksborrow',
            name='borrower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='Borrower'),
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(auto_now_add=True, help_text='Creates automatically', verbose_name='Reserved Date')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Date/time when reservation expires', null=True, verbose_name='Expiration Date')),
                ('reservation_status', models.CharField(choices=[('reserved', 'Reserved a book'), ('reservation_expired', 'Reservation expired'), ('reservation_canceled', 'Reservation canceled'), ('wishlist', 'Out of stock, added to wishlist'), ('picked_up', 'Picked up the book')], default='reserved', max_length=50, verbose_name='Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='library_app.book', verbose_name='Book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Borrower')),
            ],
            options={
                'verbose_name': 'Book Reservation',
                'verbose_name_plural': 'Book Reservations',
                'ordering': ['-reserved_date'],
            },
        ),
    ]
