# Generated by Django 5.0.6 on 2024-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_booksborrow_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservation',
            name='reservation_status',
            field=models.CharField(choices=[('reserved', 'Reserved a book'), ('reservation_expired', 'Reservation expired'), ('reservation_canceled', 'Reservation canceled'), ('wishlist', 'Out of stock, added to wishlist'), ('picked_up', 'Picked up the book')], default='reserved', max_length=50, verbose_name='Reservation Status'),
        ),
    ]
